### ISSUE TITLE
Read the RBAC configuration from ConfigMap

### ISSUE THREAD

**Issue by memoliyasti** [hivemq/hivemq-file-rbac-extension#26]
Hi all,

I am trying to configure HiveMQ Broker with RBAC configuration via using configmap. I am deploying it with Kubernetes Operator to K8s cluster.  However, configmap I created is set under the conf folder on hivemq-file-rbac-extension and it still continues to read default values. user1/pass1
I would like to be enlightened about point I miss.

I am adding the cm and values file values.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hivemq-file-rbac-extension
  namespace: {{ .Release.Namespace }}
data:
  config.xml: |-
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <file-rbac>
        <users>
            <user>
                <name>test</name>
                <password>12345</password>
                <roles>
                    <id>role1</id>
                </roles>
            </user>
        </users>
        <roles>
            <role>
                <id>role1</id>
                <permissions>
                    <permission>
                        <topic>#</topic>
                    </permission>
                    <permission>
                        <topic>#</topic>
                        <activity>PUBLISH</activity>
                        <retain>RETAINED</retain>
                    </permission>
                    <permission>
                        <topic>#</topic>
                        <activity>SUBSCRIBE</activity>
                    </permission>
                </permissions>
            </role>
            <role>
                <id>superuser</id>
                <permissions>
                    <permission>
                        <topic>#</topic>
                    </permission>
                </permissions>
            </role>
        </roles>
    </file-rbac>

  extension-config.xml: |-
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <extension-configuration>
    
        <!-- Reload interval for credentials in seconds -->
        <credentials-reload-interval>60</credentials-reload-interval>
    
        <!-- If the credentials file is using HASHED or PLAIN passwords -->
        <password-type>PLAIN</password-type>
    
    </extension-configuration>


```

```yaml
  - name: hivemq-file-rbac-extension
    enabled: true
    # Defines if your custom extension supports hot-reload of its configuration, or if it needs to be restarted on configuration changes.
    supportsHotReload: true
    # The ConfigMap name that contains the extension configuration (will be mounted into the subfolder "conf" of the extension folder).
    configMapName: "hivemq-file-rbac-extension"
    # The Secret name that contains request headers for the custom extension download.
    requestHeaderSecretName: ""
    # The URI to download the custom extension (as .zip distribution).
    extensionUri: "https://www.hivemq.com/releases/extensions/hivemq-file-rbac-extension-4.5.3.zip"
```

And also I would like to let you know about error I get when I set credentials.xml instead of config.xml

When I check hivemq-platform object, it want to see config.xml for hivemq-file-rbac-extension CM I created.

<img width="1704" alt="image" src="https://github.com/hivemq/hivemq-file-rbac-extension/assets/79761080/51d5dce5-c2af-4528-bbd2-622e62d30aee">

And this shows how extension folder looks like

<img width="671" alt="image" src="https://github.com/hivemq/hivemq-file-rbac-extension/assets/79761080/905f396a-7c82-48e8-aaad-faa35ad0d61f">

HiveMQ Version : 4.25.1
Opeartor: 1.1.0

Since I am not familiar with XML configuration, I would like to know what I am doing wrong.
If you need more details you want me to provide, please let me know.

Thank you in advance
